Perficient/Models/Client.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Perficient.Models
{
    public class Client
    {
        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }

        [Required]
        [StringLength(255)]
        public string Street { get; set; }

        [Required]
        [StringLength(255)]
        public string City { get; set; }

        [Required]
        public string State { get; set; }

        [Required]
        public string ZipCode { get; set; }

        [Required]
        [StringLength(255)]
        public string Email { get; set; }

        [Required]
        public string Phone { get; set; }

        public DateTime DateTime { get; set; }
    }
}

Perficient/ViewModels/ClientViewModel.cs
using Perficient.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Perficient.ViewModels
{
    public class ClientViewModel
    {
        [Required(ErrorMessage = "Name is Required")]
        [StringLength(255)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Street Address is Required")]
        [StringLength(255)]
        [Display(Name = "Street Address")]
        public string Street { get; set; }

        [Required(ErrorMessage = "City is Required")]
        [StringLength(255)]
        public string City { get; set; }

        [Required(ErrorMessage = "State is Required")]
        public string State { get; set; }

        [Required(ErrorMessage = "Zip Code is Required")]
        [RegularExpression(@"^[0-9]{5}(?:-[0-9]{4})?$", ErrorMessage = "Invalid Zip Code")]
        [Display(Name = "Zip Code (e.g., 12345-1234)")]
        public string ZipCode { get; set; }

        [Required(ErrorMessage = "Email is Required")]
        [EmailAddress]
        [StringLength(255)]
        public string Email { get; set; }

        [Required(ErrorMessage = "Phone Number is Required")]
        [Phone]
        [Display(Name = "Phone Number")]
        public string Phone { get; set; }

        public IEnumerable<Attendee> Attendees { get; set; }
    }
}

Perficient/Controllers/AttendeesController.cs
using Perficient.Models;
using Perficient.ViewModels;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Perficient.Controllers
{
    public class AttendeesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AttendeesController()
        {
            _context = new ApplicationDbContext();
        }

        public ActionResult Register()
        {
            var viewModel = new AttendeeViewModel
            {
                Clients = _context.Clients.ToList()
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Register(AttendeeViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Clients = _context.Clients.ToList();
                return View("Register", viewModel);
            }

            var client = _context.Clients.Single(c => c.Id == viewModel.Client);

            var attendee = new Attendee
            {
                FirstName = viewModel.FirstName,
                LastName = viewModel.LastName,
                Email = viewModel.Email,
                DateTime = DateTime.Now,
                Client = client
            };

            _context.Attendees.Add(attendee);
            _context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Attendees()
        {
            return View();
        }
    }
}

Perficient/Controllers/ClientsController.cs
using Perficient.Models;
using Perficient.ViewModels;
using System;
using System.Web.Mvc;

namespace Perficient.Controllers
{
    public class ClientsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClientsController()
        {
            _context = new ApplicationDbContext();
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(ClientViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View("Register", viewModel);

            var client = new Client
            {
                Name = viewModel.Name,
                Street = viewModel.Street,
                City = viewModel.City,
                State = viewModel.State,
                ZipCode = viewModel.ZipCode,
                Email = viewModel.Email,
                Phone = viewModel.Phone,
                DateTime = DateTime.Now
            };

            _context.Clients.Add(client);
            _context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
    }
}

Perficient/Views/Clients/Register.cshtml
@model Perficient.ViewModels.ClientViewModel

@{
    ViewBag.Title = "Register";
}

<div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-4 text-center">
        <h2>Register</h2>
        <br />
        <p>Please select a type of registration:</p>
        <p>@Html.ActionLink("Client", "Register", "Clients", null, new { @class = "btn btn-primary" })@Html.ActionLink("Attendee", "Register", "Attendees", null, new { @class = "btn btn-default" })</p>
        <br />
        @using (Html.BeginForm("Register", "Clients"))
        {
            <div class="form-group">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Name) })
                @Html.ValidationMessageFor(m => m.Name)
            </div>
            <div class="form-group">
                @Html.TextBoxFor(m => m.Street, new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Street) })
                @Html.ValidationMessageFor(m => m.Street)
            </div>
            <div class="form-group">
                @Html.TextBoxFor(m => m.City, new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.City) })
                @Html.ValidationMessageFor(m => m.City)
            </div>
            <div class="form-group">
                @Html.TextBoxFor(m => m.State, new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.State) })
                @Html.ValidationMessageFor(m => m.State)
            </div>
            <div class="form-group">
                @Html.TextBoxFor(m => m.ZipCode, new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.ZipCode) })
                @Html.ValidationMessageFor(m => m.ZipCode)
            </div>
            <div class="form-group">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Email) })
                @Html.ValidationMessageFor(m => m.Email)
            </div>
            <div class="form-group">
                @Html.TextBoxFor(m => m.Phone, new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Phone) })
                @Html.ValidationMessageFor(m => m.Phone)
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        }
    </div>
    <div class="col-md-4">
    </div>
</div>

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}